"""1084: exact port-fiber intertwining and the unchanged receiver task.
Default: JSON to stdout only.  --check: read-only comparison with saved results.
Original 444 rewriting is reused through the existing migration runtime.
No full 17496-by-17496 matrix, new dynamics, or parameter scan is used.
"""
from collections import Counter
from fractions import Fraction as Q
from pathlib import Path
import argparse, hashlib, json, math, platform, sys
import numpy as np

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
sys.path.insert(0,str(ROOT/'scripts'))
from research_layout import Layout,ResearchRuntime


def fraction(q):
    q=Q(q)
    return {'numerator':q.numerator,'denominator':q.denominator,'decimal':float(q)}


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def run():
    checks=[]
    def require(name,condition):
        if not bool(condition):
            raise AssertionError(name)
        checks.append(name)
    with ResearchRuntime(Layout(),'late').installed():
        import partner_port_carrier_audit as old
        sector=old.trees_model.six_vertex_sector()
        graphs=sector[0]
        graph_index={g:i for i,g in enumerate(graphs)}
        fibers=[old.lifts(g,6,3) for g in graphs]
        codes=[p for family in fibers for p in family]
        address_graph={p:g for g,family in enumerate(fibers) for p in family}
        def chi(p):
            # Complete degree-three center 2: owners in physical port order.
            owners=[p[6+s]//3 for s in range(3)]
            return (-1)**sum(owners[a]>owners[b]
                            for a in range(3) for b in range(a+1,3))
        require('six disjoint complete legal fibers of size 2916',
                len(graphs)==6 and all(len(f)==2916 for f in fibers)
                and len(address_graph)==17496)
        require('equal source populations and orthogonal character columns',
                all(sum(chi(p) for p in f)==0 for f in fibers))
        # Integer unnormalised columns have Z^*Z=2916 I.  Accumulate actual
        # matrix products one column at a time instead of allocating Fhat.
        fplus=np.zeros((6,6),dtype=np.int64)
        fminus=np.zeros((6,6),dtype=np.int64)
        transition_count=0
        max_row_weight=0
        edge_intertwining=True
        for column,family in enumerate(fibers):
            reference=family[0]
            for target,weight in old.port_flips(reference,6,3).items():
                row=address_graph[target]
                fplus[row,column]+=weight
                fminus[row,column]+=weight*chi(reference)*chi(target)
            received_plus=Counter()
            received_minus=Counter()
            for p in family:
                targets=old.port_flips(p,6,3)
                max_row_weight=max(max_row_weight,sum(targets.values()))
                transition_count+=len(targets)
                for q,weight in targets.items():
                    received_plus[q]+=weight
                    received_minus[q]+=weight*chi(p)
            for q in codes:
                row=address_graph[q]
                edge_intertwining &= received_plus[q]==int(fplus[row,column])
                edge_intertwining &= received_minus[q]==chi(q)*int(fminus[row,column])
        require('all original rewrites give exact two integer intertwiners',
                edge_intertwining and transition_count==69984
                and max_row_weight==4)
        require('two quotient generators are symmetric and mixed character squares to 4I',
                np.array_equal(fplus,fplus.T) and np.array_equal(fminus,fminus.T)
                and np.array_equal(fminus@fminus,4*np.eye(6,dtype=np.int64)))
        require('original graph quotient and signed loop differ',
                np.array_equal(fplus,sector[3])
                and int(fplus[0,1]*fplus[1,2]*fplus[2,0])==1
                and int(fminus[0,1]*fminus[1,2]*fminus[2,0])==-1)
        # All local S3 groups are generated by these two transpositions.
        # Here every assignment of the actual initial graph is checked.
        symmetry_ok=True
        symmetry_count=0
        for p in fibers[0]:
            for subject in range(6):
                for a,b in ((0,1),(1,2)):
                    local=[list(range(3)) for _ in range(6)]
                    local[subject][a],local[subject][b]=local[subject][b],local[subject][a]
                    q=old.rename_port(p,6,3,list(range(6)),local)
                    symmetry_ok &= address_graph[q]==0
                    symmetry_ok &= chi(q)==(-1 if subject==2 else 1)*chi(p)
                    symmetry_count+=1
        require('full initial source local-port group character, not only occupied subgroup',
                symmetry_ok and symmetry_count==34992)
        # The 24-dimensional convenience sector fixes occupied leaf ports and
        # the 1--2 central edge at port 0 of both centers.  Its invariance is
        # checked against original rewrites; no physical projection is applied.
        leaves=(0,3,4,5)
        small=[p for p in codes if p[3]==6 and p[6]==3
               and all(p[3*i]>=0 and p[3*i+1]==p[3*i+2]==-1 for i in leaves)]
        small_index={p:i for i,p in enumerate(small)}
        a24=np.zeros((24,24),dtype=np.int64)
        zplus=np.zeros((24,6),dtype=np.int64)
        zminus=np.zeros((24,6),dtype=np.int64)
        for p,col in small_index.items():
            for q,weight in old.port_flips(p,6,3).items():
                a24[small_index[q],col]+=weight
            g=address_graph[p]
            zplus[col,g]=1
            zminus[col,g]=1 if p[7]//3<p[8]//3 else -1
        small_fminus=zminus.T@a24@zminus//4
        gauge=np.diag([1,1,-1,1,-1,-1])
        require('24-state convenience sector and 4-term character intertwiners',
                len(small)==24
                and np.array_equal(zplus.T@zplus,4*np.eye(6,dtype=np.int64))
                and np.array_equal(zminus.T@zminus,4*np.eye(6,dtype=np.int64))
                and np.array_equal(a24@zplus,zplus@fplus)
                and np.array_equal(a24@zminus,zminus@small_fminus)
                and np.array_equal(fminus,gauge@small_fminus@gauge))
        # The nonzero sign character cannot be removed by rephasing graph
        # vertices: triangle products differ.  This is a graph-quotient fact,
        # not yet the receiver witness.  Use the original 443 task below.
        laplacians=[]
        for graph in graphs:
            lap=np.zeros((6,6),dtype=np.int64)
            for a,b in graph:
                lap[a,a]+=1;lap[b,b]+=1;lap[a,b]-=1;lap[b,a]-=1
            laplacians.append(lap)
        time=Q(7,10);degree=40
        amplitude_tail=Q(3**7*7**41,math.factorial(41))
        probability_error=2*amplitude_tail+amplitude_tail**2
        probability_approximants=[]
        rows=[]
        for label,flip in (('uniform',fplus),('center2_sign',fminus)):
            h=np.kron(np.eye(6,dtype=np.int64),flip)
            for g,lap in enumerate(laplacians):
                pg=np.zeros((6,6),dtype=np.int64);pg[g,g]=1
                h-=np.kron(lap,pg)
            row_bound=int(np.max(np.sum(abs(h),axis=1)))
            require(label+' original single-excitation integer generator and norm bound',
                    np.array_equal(h,h.T) and row_bound<=10)
            ho=h.astype(object)
            vec=np.zeros(36,dtype=object);vec[0]=1
            real=[Q(0)]*6;imag=[Q(0)]*6;moments=[]
            for k in range(degree+1):
                receiver=[int(v) for v in vec[30:36]]
                moments.append(receiver)
                coefficient=time**k/math.factorial(k)
                sign=(1,-1,-1,1)[k%4]
                dest=real if k%2==0 else imag
                for j in range(6):dest[j]+=sign*coefficient*receiver[j]
                vec=ho@vec
            probability=sum(x*x+y*y for x,y in zip(real,imag))
            probability_approximants.append(probability)
            series={}
            for n in range(9):
                coefficient=Q(0)
                for k in range(n+1):
                    ell=n-k
                    if (ell-k)%2==0:
                        coefficient+=(-1)**(((ell-k)%4)//2)*Q(
                            sum(x*y for x,y in zip(moments[k],moments[ell])),
                            math.factorial(k)*math.factorial(ell))
                if coefficient:series[str(n)]=str(coefficient)
            require(label+' first nonzero receiver coefficients',
                    series=={'6':'7/36','8':('-607/1440' if label=='uniform' else '-443/1440')})
            rows.append({'source':label,'generator_absolute_row_sum':row_bound,
                         'receiver_probability_taylor40':fraction(probability),
                         'receiver_probability_interval':{
                             'lower':fraction(probability-probability_error),
                             'upper':fraction(probability+probability_error)},
                         'exact_series_through_order8':series})
        gap=probability_approximants[1]-probability_approximants[0]-2*probability_error
        half_width=Q(1,100000)
        window_gap=gap-40*half_width
        require('strict finite-time original receiver probability separation',gap>Q(1,400))
        require('entire fixed time window separation',window_gap>Q(1,500))
        sources=[ROOT/'research_cognition_physics/archive_429_466/444/partner_port_carrier_audit.py',ROOT/'research_cognition_physics/archive_429_466/research_note_444.md',
                 ROOT/'research_cognition_physics/archive_429_466/research_note_443.md',
                 ROOT/'research_cognition_physics/archive_429_466/442/branching_tree_distance_audit.py',ROOT/'scripts/research_layout.py']
        source_hashes={str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in sources}
        return {'round':1084,'validation_group_count':5,'assertion_count':len(checks),
                'assertions':checks,'science_increment_groups':1,
                'source_hashes':source_hashes,
                'full_port_model':{'subject_count':6,'capacity':3,
                    'graph_order':[sorted(map(list,g)) for g in graphs],
                    'address_dimension':17496,'fiber_dimension':2916,
                    'integer_column_normalizer':54,
                    'original_directed_rewrites_checked':transition_count,
                    'source_group_generator_checks':symmetry_count,
                    'full_local_port_group':'S3^6',
                    'minus_source_character':'sign at center 2; trivial at other five subjects',
                    'same_graph_and_all_address_populations':True,
                    'orthogonal_source_states':True,
                    'source_density_matrices_invariant_under_all_local_port_renamings':True,
                    'f_uniform':fplus.tolist(),'f_center2_sign':fminus.tolist(),
                    'triangle_0_1_2_products':[1,-1]},
                'small_sector':{'dimension':24,'fiber_dimension':4,
                    'fixed_leaf_ports':[0,0,0,0],'fixed_central_edge_ports':[0,0],
                    'renaming_subgroup':'S2 x S2',
                    'f_center2_leaf_sign':small_fminus.tolist(),
                    'full_to_small_graph_phase_gauge':[1,1,-1,1,-1,-1]},
                'actual_receiver_task':{'source_subject':0,'receiver_subject':5,
                    'initial_graph_index':0,'initial_data':'one excitation at subject 0, all others 0',
                    'effect':'excitation projector on original subject 5 only',
                    'kappa':1,'J':1,'removed_common_single_excitation_scalar':5,
                    'time':str(time),'taylor_degree':degree,'hamiltonian_norm_upper':10,
                    'amplitude_tail_upper':fraction(amplitude_tail),
                    'per_probability_error_upper':fraction(probability_error),
                    'sources':rows,'probability_gap_certified_lower':fraction(gap),
                    'window_half_width':str(half_width),'gap_lipschitz_upper':40,
                    'window_probability_gap_certified_lower':fraction(window_gap),
                    'window_simple_gap':'1/500','lowest_probability_difference_coefficient':'41/360 at t^8'},
                'scope':{'same_original_H_and_actual_receiver':True,
                    'new_physical_instrument_added':False,'port_character_preparation_derived':False,
                    'uniform_preparation_can_be_removed_by_graph_identity_and_renaming_invariance':False,
                    'all_legal_port_states_classified':False,'actual_space_dimension_derived':False,
                    'complete_cognitive_principles_refuted':False},
                'runtime':{'python':platform.python_version(),'numpy':np.__version__},
                'checker_sha256':sha(__file__)}


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='read-only exact comparison with saved JSON')
    args=parser.parse_args();result=run()
    if args.check:
        path=HERE/'results.json'
        if result!=json.loads(path.read_text(encoding='utf-8')):
            raise AssertionError('saved results differ from recomputation')
        print(json.dumps({'round':1084,'status':'exact_saved_results_match',
             'validation_group_count':result['validation_group_count'],
             'assertion_count':result['assertion_count'],
             'checker_sha256':result['checker_sha256'],'results_sha256':sha(path)},indent=2))
    else:print(json.dumps(result,ensure_ascii=False,indent=2))

if __name__=='__main__':main()
