"""Working 858: original radial canonical data versus state-dependent cells.
Exact finite-stencil algebra; not an Einstein-constraint or quantum-domain proof.
"""
from pathlib import Path
from fractions import Fraction as F
import argparse,json
HERE=Path(__file__).resolve().parent;TARGET=HERE/'material_cell_canonical_probe_results.json'
def K(h,s):
    f=2-(h*h+s*s)/6;assert f>0
    u=(h,s)
    return [[F(i==j)/f+u[i]*u[j]/(6*f*f) for j in range(2)] for i in range(2)]
def inv(M):
    d=M[0][0]*M[1][1]-M[0][1]*M[1][0]
    return [[M[1][1]/d,-M[0][1]/d],[-M[1][0]/d,M[0][0]/d]]
def mv(M,v):return [sum(a*b for a,b in zip(row,v)) for row in M]
def run():
    spacing=F(1,4);w0=spacing**3;eta=F(8)
    def at(x,y,z,beta):
        h,s=F(1),F(1,2)+x;metric=K(h,s)
        velocity=[1+(1+beta)*y,2+z]
        momentum=[w0*v for v in mv(metric,velocity)]
        recovered=[v/w0 for v in mv(inv(metric),momentum)]
        assert recovered==velocity
        A=-recovered[0]**2
        B=1-recovered[1]**2
        return dict(h=h,s=s,A=A,B=B,p=momentum,K=metric)
    rows=[]
    for beta in (F(-1,4),F(0),F(1,4),F(1,2)):
        xp,xm=at(spacing,0,0,beta),at(-spacing,0,0,beta)
        yp,ym=at(0,spacing,0,beta),at(0,-spacing,0,beta)
        zp,zm=at(0,0,spacing,beta),at(0,0,-spacing,beta)
        sx=(xp['s']-xm['s'])/(2*spacing)
        Ay=(yp['A']-ym['A'])/(2*spacing)
        Bz=(zp['B']-zm['B'])/(2*spacing)
        n=eta*sx*Ay*Bz;assert n>0
        wR=1/n;assert wR==w0/(1+beta)
        # The momentum shift is generated by a linear combination of the same
        # original h,s observables with coefficients frozen at the base data.
        for x,y,z in ((0,spacing,0),(0,-spacing,0),(0,0,spacing)):
            old=at(x,y,z,F(0));new=at(x,y,z,beta)
            g=[w0*v for v in mv(old['K'],[y,F(0)])]
            assert new['p']==[a+beta*b for a,b in zip(old['p'],g)]
        rows.append(dict(beta=str(beta),s_x=str(sx),A_y=str(Ay),B_z=str(Bz),
            material_density=str(n),material_cell_volume=str(wR),
            fixed_weight=str(w0),fixed_inverse_weight=str(1/w0),material_inverse_weight=str(1/wR)))
    return dict(kind='round_858_working_probe',formal_reports=857,newly_published_numbered_groups=0,
        all_checks_passed=True,grid_spacing=str(spacing),label_density_input=str(eta),
        canonical_radial_metric=[[str(v) for v in row] for row in K(F(1),F(1,2))],rows=rows,
        base_cell_volume_matches_fixed_weight=True,
        material_volume_poisson_bracket_with_G_at_base=str(-w0),
        material_inverse_volume_poisson_bracket_with_G=str(1/w0),
        old_fixed_weight_poisson_bracket_with_G='0',
        fully_transported_canonical_mapping_classified=False,
        original_quantum_reference_operators_or_gravity_constraints_completed=False)
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');args=p.parse_args();r=run()
    if args.write:
        assert not TARGET.exists();TARGET.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    else:assert r==json.loads(TARGET.read_text('utf-8'))
    print(json.dumps(r,ensure_ascii=False,indent=2))
