"""Reproduce 853, check frozen evidence, publication links and stated scope."""
from pathlib import Path
import argparse,ast,hashlib,json,re,sys
sys.dont_write_bytecode=True
HERE=Path(__file__).resolve().parent;STAGE=HERE.parent;ROOT=HERE.parents[2]
sys.path.insert(0,str(ROOT/'scripts'))
from research_layout import Layout
import native_receiver_content as experiment
RECEIPT=HERE/'research_round_853_checks.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def verify(writing=False):
    assert experiment.run()==json.loads(experiment.TARGET.read_text('utf-8'))
    for n in range(776,853):
        old=json.loads((STAGE/f'{n}/research_round_{n}_checks.json').read_text('utf-8'))
        for key in ('frozen_inputs','new_scientific_and_entry_files'):
            for name,digest in old[key].items():assert sha(ROOT/name)==digest,name
    history=Layout().verify()
    note=STAGE/'research_note_853.md';body=note.read_text('utf-8')
    assert body.count('$$')==22 and '	' not in body
    assert re.findall(r'\\tag\{(\d+)\}',body)==[str(n) for n in range(1,12)]
    docs=[note,STAGE/'854/drafts/STATUS.md',STAGE/'_shared/notes/unified_physics_condition_ledger_current.md']
    docs += [STAGE/p for p in ('README.md','文件索引.md','阶段成果总览.md','跨阶段主题索引.md')]
    docs += [STAGE.parent/p for p in ('README.md','research_direction.md','RESEARCH_STATE.md')]
    docs += list((HERE/'drafts').glob('*.md'))
    links=0
    for doc in docs:
        for target in re.findall(r'\]\(([^)]+)\)',doc.read_text('utf-8-sig')):
            if re.match(r'^[a-zA-Z]+://',target) or target.startswith('#'):continue
            path=(doc.parent/target.split('#')[0].strip('<>')).resolve()
            assert path.exists() or (writing and path==RECEIPT.resolve()),(str(doc),target)
            links+=1
    numbers=[]
    for p in STAGE.parent.rglob('research_note_*.md'):
        m=re.fullmatch(r'research_note_(\d+).md',p.name)
        if p.parent.name.startswith('archive_') and m:numbers.append(int(m[1]))
    assert sorted(n for n in numbers if n<=853)==list(range(1,854))
    frozen=[STAGE/'852/research_round_852_checks.json',HERE/'drafts/STATUS.md',HERE/'drafts/research_note_853_working.md']
    frozen += [STAGE/f'research_note_{n}.md' for n in (783,793,795,796,798,801,809,814,815,829,842,844,847,851,852)]
    fresh=[note,STAGE/'854/drafts/STATUS.md',HERE/'native_receiver_content.py',experiment.TARGET,Path(__file__)]
    for p in fresh:
        if p.suffix=='.py':ast.parse(p.read_text('utf-8'),filename=str(p))
    return dict(round=853,date='2026-10-05',all_checks_passed=True,fresh_test_groups=1,
        cumulative_numbered_test_groups_from_852=3638,saved_result_reproduced=True,
        historical_manifest_evidence=history,previous_776_through_852_frozen_hashes_verified=True,
        historical_science_rerun=False,formal_reports=853,local_links_checked=links,display_equations=11,
        frozen_inputs={str(p.relative_to(ROOT)):sha(p) for p in frozen},
        new_scientific_and_entry_files={str(p.relative_to(ROOT)):sha(p) for p in fresh},
        argument_scope='An explicitly enlarged local formal EFT with three neutral degenerate Dirac receiver doublets and calibrated material couplings has finite internal CAR outputs generated by its own action. A specified six-coupling coefficient of the output parity has the original nonzero hbar-cubed content witness. Receiver sources and input preparation are included. This does not prove that the unextended branch fails, finite-coupling continuum probabilities, autonomous preparation or readout, or the full unification goal.',
        output_projectors_come_from_the_same_action=True,
        prescribed_content_transfer_not_merely_receiver_disturbance=True,
        new_receiver_species_profiles_preparation_and_couplings_are_inputs=True,
        full_material_variations_and_new_quantum_loops_retained=True,
        original_852_branch_without_receivers_disproved=False,
        exact_finite_diagnostic_not_continuum_finite_coupling=True,
        full_curved_PDE_or_loop_coefficients_computed=False,
        free_input_entropy_claim_not_interacting_total_entropy=True,
        spacetime_group_action_remain_inputs=True,full_goal_completed=False,
        visual_checks_performed=False,app_goal_changed=False)
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');args=p.parse_args()
    if args.write:assert not RECEIPT.exists(),'Do not overwrite a frozen receipt.'
    result=verify(args.write)
    if args.write:RECEIPT.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    else:
        old=json.loads(RECEIPT.read_text('utf-8'))
        for k in ('frozen_inputs','new_scientific_and_entry_files','argument_scope'):assert old[k]==result[k],k
    print(json.dumps({k:v for k,v in result.items() if k not in ('frozen_inputs','new_scientific_and_entry_files')},ensure_ascii=False,indent=2))
